version: 2.1

workflows:
  main:
    jobs:
      - run-tests

jobs:
  run-tests:
    docker:
      - image: aotuai/brainframe_build_env:0.29.2.2
    resource_class: medium
    parallelism: 2
    steps:
      # Add pull dependencies
      - run: mkdir -m 700 ~/.ssh/ &&
             echo -e "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config
      - run: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A4B469963BF863CC
      - run: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F60F4B3D7FA2AF80
      - run: apt update &&
             apt-get install -y ssh git git-lfs &&
             git lfs install
      # Pull the project
      - checkout
      # Install test dependencies. The following line invalidates the cache whenever a new vcap version is released
      - run: |
          pip3 install vcap==FAKE_VERSION &> available-vcap-versions.txt || true
          pip3 install vcap_utils==FAKE_VERSION 2>> available-vcap-versions.txt || true
      - restore_cache:
          key: v3-python-cache--{{ checksum "tests/requirements.txt" }}--{{ checksum "available-vcap-versions.txt" }}
      - run: >
          pip3 install --pre --quiet -r tests/requirements.txt
      - save_cache:
          key: v3-python-cache--{{ checksum "tests/requirements.txt" }}--{{ checksum "available-vcap-versions.txt" }}
          paths:
            - /root/.cache/pip
      # Run Capsule tests in multiple containers. Use circleci commands to split the test files up.
      - run: >
          circleci tests glob **/test*.py |
          circleci tests split --split-by=timings --timings-type=classname |
          xargs python3 -m pytest --junitxml=test-results/junit.xml -x -s -vvv
      - store_test_results:
          path: test-results
